[package]
name = "replay-runner"
version = "0.1.0"
edition = "2024"

[dependencies]
anyhow = "1.0"
async-process = "2.3.1"
futures = "0.3.31"
itertools = "0.14.0"
tempfile = "3.20.0"
async-std = { version = "1.12", features = ["attributes"] }
zip = "4.0.0"
