[package]
name = "cli"
version = "0.1.0"
edition = "2024"

[dependencies]
anyhow = "1.0.98"
async-std = { version = "1.13.1", features = ["attributes"] }
clap = { version = "4.5.41", features = ["derive"] }
replay-runner = { path = "../replay-runner" }
replay-script = { version = "0.1.0", path = "../replay-script" }
serde = { version = "1.0.219", features = ["derive"] }
serde_json = "1.0.141"

[dev-dependencies]
test-utils = { path = "../test-utils" }
