[package]
name = "cli"
version = "0.1.0"
edition = "2024"

[dependencies]
anyhow = { workspace = true }
tokio = { workspace = true }
clap = { workspace = true }
replay-runner = { path = "../replay-runner" }
replay-script = {  path = "../replay-script" }
serde = { workspace = true }
serde_yaml = { workspace = true }

[dev-dependencies]
test-utils = { path = "../test-utils" }
