[package]
name = "factorio-replay-runner"
version = "0.1.0"
edition = "2024"

[dependencies]
async-process = "2.3.1"
itertools = "0.14.0"
tempfile = "3.20.0"
tokio = { version="1.45.1", features = ["full"] }
zip = "4.0.0"
