[package]
name = "replay-script"
version = "0.1.0"
edition = "2024"

[dependencies]
itertools = { workspace = true }
serde = { workspace = true }
strum = { workspace = true }

[build-dependencies]
glob = { workspace = true }
